name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4

      - name: Run tests
        run: |
          docker run --rm -it -v $PWD:/fiware openresty/openresty:1.19.9.1-10-alpine-fat /bin/bash -c 'cd /fiware && ./run_tests.sh'