name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4

      - name: Run tests
        run: ./run_tests.sh